import { Navbar } from "@/components/navbar";
import { Footer } from "@/components/landing/footer";
import type { Metadata } from "next";

export const metadata: Metadata = {
  title: "Terms of Service — StoxPulse",
  description: "StoxPulse terms of service. Rules and guidelines for using our platform.",
  alternates: {
    canonical: "https://stoxpulse.com/terms",
  },
};

export default function TermsPage() {
  return (
    <>
      <Navbar />
      <main className="mx-auto max-w-3xl px-6 pt-32 pb-24">
        <h1 className="text-3xl font-bold tracking-tight md:text-4xl">Terms of Service</h1>
        <p className="mt-2 text-sm text-muted-foreground">Last updated: March 5, 2026</p>

        <div className="mt-10 space-y-8 text-sm text-muted-foreground leading-relaxed">
          <section>
            <h2 className="text-lg font-semibold text-foreground mb-3">1. Acceptance of Terms</h2>
            <p>
              By accessing or using StoxPulse (&quot;the Service&quot;), you agree to be bound by
              these Terms of Service. If you do not agree, do not use the Service.
            </p>
          </section>

          <section>
            <h2 className="text-lg font-semibold text-foreground mb-3">2. Description of Service</h2>
            <p>
              StoxPulse provides AI-powered stock intelligence, including earnings call analysis, SEC
              filing summaries, news aggregation, and sentiment analysis. The Service is designed for
              informational and educational purposes only.
            </p>
          </section>

          <section>
            <h2 className="text-lg font-semibold text-foreground mb-3">3. Not Financial Advice</h2>
            <p>
              StoxPulse does NOT provide investment advice, financial advice, trading advice, or any
              other sort of professional advice. The AI-generated analysis, scores, summaries, and
              alerts are for informational purposes only. You should not make any investment decision
              based solely on information provided by StoxPulse. Always consult a qualified financial
              advisor before making investment decisions.
            </p>
          </section>

          <section>
            <h2 className="text-lg font-semibold text-foreground mb-3">4. AI-Generated Content</h2>
            <p>
              Content generated by our AI systems may contain errors, inaccuracies, or omissions. AI
              analysis is probabilistic in nature and should not be treated as fact. We make no
              guarantees regarding the accuracy, completeness, or timeliness of AI-generated content.
              You are responsible for independently verifying any information before acting on it.
            </p>
          </section>

          <section>
            <h2 className="text-lg font-semibold text-foreground mb-3">5. Account Responsibilities</h2>
            <p>
              You are responsible for maintaining the security of your account credentials. You must
              provide accurate information when creating an account. You may not share your account
              or use the Service for any unlawful purpose.
            </p>
          </section>

          <section>
            <h2 className="text-lg font-semibold text-foreground mb-3">6. Subscription & Billing</h2>
            <p>
              Paid plans are billed monthly or annually as selected. You may cancel at any time, and
              your access will continue until the end of the current billing period. Refunds are
              handled on a case-by-case basis. Prices may change with 30 days&apos; notice.
            </p>
          </section>

          <section>
            <h2 className="text-lg font-semibold text-foreground mb-3">7. Limitation of Liability</h2>
            <p>
              To the maximum extent permitted by law, StoxPulse and its operators shall not be liable
              for any indirect, incidental, special, consequential, or punitive damages, including
              but not limited to loss of profits, data, or investment losses, arising from your use
              of the Service. Our total liability shall not exceed the amount you paid for the
              Service in the 12 months preceding the claim.
            </p>
          </section>

          <section>
            <h2 className="text-lg font-semibold text-foreground mb-3">8. Intellectual Property</h2>
            <p>
              All content, features, and functionality of StoxPulse are owned by us and are protected
              by copyright, trademark, and other intellectual property laws. You may not reproduce,
              distribute, or create derivative works without our prior written consent.
            </p>
          </section>

          <section>
            <h2 className="text-lg font-semibold text-foreground mb-3">9. Termination</h2>
            <p>
              We reserve the right to suspend or terminate your account at any time for violation of
              these terms. Upon termination, your right to use the Service ceases immediately.
            </p>
          </section>

          <section>
            <h2 className="text-lg font-semibold text-foreground mb-3">10. Changes to Terms</h2>
            <p>
              We may update these terms from time to time. Continued use of the Service after changes
              constitutes acceptance of the new terms. Material changes will be communicated via email
              or in-app notification.
            </p>
          </section>

          <section>
            <h2 className="text-lg font-semibold text-foreground mb-3">11. Contact</h2>
            <p>
              For questions about these terms, contact us at legal@stoxpulse.com.
            </p>
          </section>
        </div>
      </main>
      <Footer />
    </>
  );
}
