import { getDashboardData } from "@/lib/data/dashboard";
import { SignalBadge, type SignalType } from "@/components/stocks/signal-badge";
import { cn } from "@/lib/utils";
import { connection } from "next/server";
import Link from "next/link";
import { tickerToSlug } from "@/data/stocks/sp500";
import type { AIStockAnalysis } from "@/lib/ai/types";

export const metadata = {
  title: "AI Signals — StoxPulse",
};

function SeverityDot({ severity }: { severity: string }) {
  return (
    <span
      className={cn(
        "inline-flex h-2 w-2 rounded-full",
        severity === "high" && "bg-negative animate-pulse",
        severity === "medium" && "bg-warning",
        severity === "low" && "bg-muted-foreground/50"
      )}
    />
  );
}

function SentimentPill({ sentiment }: { sentiment: string }) {
  return (
    <span
      className={cn(
        "inline-flex items-center rounded-full px-2 py-0.5 text-[10px] font-medium uppercase tracking-wider",
        sentiment === "bullish" && "bg-positive-muted text-positive",
        sentiment === "bearish" && "bg-negative-muted text-negative",
        sentiment === "neutral" && "bg-surface-2 text-muted-foreground"
      )}
    >
      {sentiment}
    </span>
  );
}

export default async function SignalsPage() {
  await connection();
  const data = await getDashboardData();

  // Collect AI signals
  const aiSignals: Array<{
    ticker: string;
    type: SignalType;
    title: string;
    detail: string;
    severity: "high" | "medium" | "low";
    sentiment: "bullish" | "bearish" | "neutral";
    summary?: string;
  }> = [];

  for (const analysis of data.aiAnalyses) {
    for (const sig of analysis.signals) {
      aiSignals.push({
        ticker: analysis.ticker,
        type: sig.type,
        title: sig.title,
        detail: sig.detail,
        severity: sig.severity,
        sentiment: sig.sentiment,
        summary: analysis.summary,
      });
    }
  }

  // Also add rule-based signals from price movers, insider trades, filings
  const ruleSignals: typeof aiSignals = [];
  const stockNames = new Map(data.watchlist.map((w) => [w.ticker, w.name]));

  for (const { ticker, trades } of data.recentInsiderTrades) {
    for (const trade of trades.slice(0, 2)) {
      if (trade.totalValue < 50000) continue;
      const value = trade.totalValue >= 1e6
        ? `$${(trade.totalValue / 1e6).toFixed(1)}M`
        : `$${(trade.totalValue / 1e3).toFixed(0)}K`;
      ruleSignals.push({
        ticker,
        type: trade.type === "Buy" ? "insider-buy" : "insider-sell",
        title: `${trade.name} ${trade.type === "Buy" ? "bought" : "sold"} ${value} in shares`,
        detail: `${trade.title} — ${trade.shares.toLocaleString()} shares at $${trade.pricePerShare.toFixed(2)}${!trade.isRoutine ? " (non-routine)" : ""}`,
        severity: trade.type === "Buy" ? "high" : "medium",
        sentiment: trade.type === "Buy" ? "bullish" : "bearish",
      });
    }
  }

  for (const { ticker, filings } of data.recentFilings) {
    const important = filings.filter((f) => ["10-K", "10-Q", "8-K"].includes(f.type));
    for (const filing of important.slice(0, 1)) {
      ruleSignals.push({
        ticker,
        type: "new-filing",
        title: `${filing.type} filed — ${filing.description.slice(0, 80)}`,
        detail: `Filed ${filing.date}`,
        severity: filing.type === "8-K" ? "medium" : "low",
        sentiment: "neutral",
      });
    }
  }

  const allSignals = [...aiSignals, ...ruleSignals];
  const severityOrder = { high: 0, medium: 1, low: 2 };
  allSignals.sort((a, b) => severityOrder[a.severity] - severityOrder[b.severity]);

  // AI summaries per ticker
  const summaries = new Map<string, AIStockAnalysis>();
  for (const analysis of data.aiAnalyses) {
    summaries.set(analysis.ticker, analysis);
  }

  return (
    <div className="space-y-6">
      <div>
        <h1 className="text-xl font-bold font-display tracking-tight">AI Signals</h1>
        <p className="text-sm text-muted-foreground mt-1">
          Real-time intelligence generated by AI analysis of financial data across your watchlist.
        </p>
      </div>

      {/* AI Summaries row */}
      {data.aiAnalyses.length > 0 && (
        <div className="grid grid-cols-1 md:grid-cols-2 xl:grid-cols-4 gap-3">
          {data.aiAnalyses.map((analysis) => (
            <Link
              key={analysis.ticker}
              href={`/stocks/${tickerToSlug(analysis.ticker)}`}
              className="rounded-xl border border-border/50 bg-card p-4 hover:bg-surface-2/50 transition-colors"
            >
              <div className="flex items-center justify-between mb-2">
                <span className="font-mono font-bold text-sm">{analysis.ticker}</span>
                <SentimentPill sentiment={analysis.overallSentiment} />
              </div>
              <p className="text-xs text-muted-foreground leading-relaxed line-clamp-2">
                {analysis.summary}
              </p>
              <div className="mt-2 text-[10px] text-muted-foreground">
                {analysis.signals.length} signal{analysis.signals.length !== 1 ? "s" : ""}
              </div>
            </Link>
          ))}
        </div>
      )}

      {/* Signals table */}
      <div className="rounded-xl border border-border/50 bg-card">
        <div className="px-5 py-4 border-b border-border/50">
          <div className="flex items-center gap-3">
            <h2 className="text-sm font-semibold font-display">All Signals</h2>
            <span className="text-xs text-muted-foreground">
              {allSignals.length} active
            </span>
            {aiSignals.length > 0 && (
              <span className="inline-flex items-center gap-1 rounded-full bg-brand/10 px-2 py-0.5 text-[9px] font-semibold text-brand uppercase tracking-wider">
                AI Powered
              </span>
            )}
          </div>
        </div>
        <div className="divide-y divide-border/30">
          {allSignals.length === 0 ? (
            <p className="text-sm text-muted-foreground py-12 text-center">
              No active signals. Signals are generated from your watchlist data.
            </p>
          ) : (
            allSignals.map((signal, i) => (
              <Link
                key={`${signal.ticker}-${signal.type}-${i}`}
                href={`/stocks/${tickerToSlug(signal.ticker)}`}
                className="flex items-start gap-4 px-5 py-4 hover:bg-surface-2/30 transition-colors"
              >
                <div className="shrink-0 mt-0.5">
                  <SeverityDot severity={signal.severity} />
                </div>
                <div className="flex-1 min-w-0 space-y-1">
                  <div className="flex items-center gap-2 flex-wrap">
                    <span className="font-mono font-bold text-xs">{signal.ticker}</span>
                    <SignalBadge type={signal.type} />
                    <SentimentPill sentiment={signal.sentiment} />
                  </div>
                  <p className="text-sm font-medium leading-snug">{signal.title}</p>
                  <p className="text-xs text-muted-foreground leading-relaxed">{signal.detail}</p>
                </div>
              </Link>
            ))
          )}
        </div>
      </div>
    </div>
  );
}
